<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'full_name' => 'Ahmad Syafiq Bin Ismail',
                'date_of_birth' => '2008-06-15',
                'address' => 'No. 12, Jalan Merdeka, 43000 Kajang, Selangor',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID123456',
                'emergency_contact' => '0123456789',
                'relationship' => 'Father',
                'status' => 'active',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nur Aisyah Binti Abdullah',
                'date_of_birth' => '2010-02-20',
                'address' => 'No. 45, Taman Harmoni, 54000 Kuala Lumpur',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID987654',
                'emergency_contact' => '0138765432',
                'relationship' => 'Mother',
                'status' => 'active',
                'user_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Tan Wei Ling',
                'date_of_birth' => '2009-08-10',
                'address' => 'No. 88, Jalan Bukit Indah, 81100 Johor Bahru, Johor',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID112233',
                'emergency_contact' => '0171122334',
                'relationship' => 'Mother',
                'status' => 'active',
                'user_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Mohd Amirul Bin Hassan',
                'date_of_birth' => '2011-05-12',
                'address' => 'No. 33, Taman Mawar, 75250 Melaka',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID445566',
                'emergency_contact' => '0169988776',
                'relationship' => 'Father',
                'status' => 'active',
                'user_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Siti Hawa Binti Ahmad',
                'date_of_birth' => '2012-07-30',
                'address' => 'No. 14, Jalan Teratai, 93000 Kuching, Sarawak',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID778899',
                'emergency_contact' => '0142233445',
                'relationship' => 'Mother',
                'status' => 'active',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Chan Kai Lun',
                'date_of_birth' => '2007-09-22',
                'address' => 'No. 77, Jalan Damai, 40100 Shah Alam, Selangor',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID998877',
                'emergency_contact' => '0183344556',
                'relationship' => 'Father',
                'status' => 'active',
                'user_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Leong Mei Ling',
                'date_of_birth' => '2013-03-18',
                'address' => 'No. 9, Jalan Kenanga, 75000 Alor Gajah, Melaka',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID556677',
                'emergency_contact' => '0194455667',
                'relationship' => 'Mother',
                'status' => 'active',
                'user_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Rajesh Kumar',
                'date_of_birth' => '2006-11-02',
                'address' => 'No. 66, Jalan Tenang, 81500 Pekan Nanas, Johor',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID665544',
                'emergency_contact' => '0127766554',
                'relationship' => 'Father',
                'status' => 'active',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Aisyah Binti Harun',
                'date_of_birth' => '2014-01-05',
                'address' => 'No. 21, Jalan Masjid, 88000 Kota Kinabalu, Sabah',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID443322',
                'emergency_contact' => '0173344557',
                'relationship' => 'Mother',
                'status' => 'active',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Farid Bin Mohd Zaki',
                'date_of_birth' => '2005-10-01',
                'address' => 'No. 88, Jalan Bahagia, 43200 Cheras, Selangor',
                'school' => 'SMK Sri Permata',
                'profile_photo' => 'default.png',
                'rfid_tag' => 'RFID334455',
                'emergency_contact' => '0119988775',
                'relationship' => 'Father',
                'status' => 'active',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
