<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Muhammad Admin',
                'email' => 'admin@gmail.com',
                'phone' => '017-6532057',
                'address' => 'No 50 Jalan Ungu U9/35 40150 Shah Alam',
                'status' => 'Active',
                'usertype' => 'admin',
                'email_verified_at' => now(),
                'password' => Hash::make('password'), // Encrypt the password
                'profile_photo_path' => 'profile_photos/general.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Driver One',
                'email' => 'driver_one@gmail.com',
                'phone' => '017-7266352',
                'address' => 'No 23 Jalan Ganung, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'driver',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/jason.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Driver Two',
                'email' => 'driver_two@gmail.com',
                'phone' => '012-7378384',
                'address' => 'No 24 Jalan Singa, Sungai Way',
                'status' => 'Active',
                'usertype' => 'driver',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/han.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muhammad Amin Bin Abd Rani',
                'email' => 'amin@gmail.com',
                'phone' => '011-2352374',
                'address' => 'No 23 Jalan Datuk, Kelana Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/amin.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amirah Syahirah Binti Ahmad',
                'email' => 'amirah@gmail.com',
                'phone' => '011-2323374',
                'address' => 'No 23 Jalan Datuk Onn, Taman Tun',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/mira.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad Zulkifli Bin Hassan',
                'email' => 'zulkifli@gmail.com',
                'phone' => '013-5551234',
                'address' => 'No 15 Jalan Kenanga, Kuala Lumpur',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ain Najwa Binti Mazlan',
                'email' => 'ainnajwa@gmail.com',
                'phone' => '011-2233456',
                'address' => 'No 3, Jalan SS9A/2, Sungai Way, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hazim Bin Rahman',
                'email' => 'hazimrahman@gmail.com',
                'phone' => '012-5567890',
                'address' => 'No 12, Jalan SS9A/5, Sungai Way, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nurul Syafiqah Binti Halim',
                'email' => 'syafiqahhalim@gmail.com',
                'phone' => '013-8844221',
                'address' => 'No 23, Jalan SS6/2, Kelana Jaya, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khairul Anuar Bin Idris',
                'email' => 'khairulanuar@gmail.com',
                'phone' => '017-9324455',
                'address' => 'No 45, Jalan SS5B/4, Kelana Jaya, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mohd Azim Bin Khalid',
                'email' => 'azimkhalid@gmail.com',
                'phone' => '012-9976231',
                'address' => 'No 33, Jalan SS9A/7, Sungai Way, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rozita Binti Abu',
                'email' => 'rozitaabu@gmail.com',
                'phone' => '016-8827364',
                'address' => 'No 7, Jalan SS6/7, Kelana Jaya, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Azlina Binti Hashim',
                'email' => 'azlinahashim@gmail.com',
                'phone' => '011-2837462',
                'address' => 'No 20, Jalan SS1/5, Kampung Tunku, Petaling Jaya',
                'status' => 'Active',
                'usertype' => 'user',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'profile_photo_path' => 'profile_photos/no-profile.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
